import React from 'react';
import { useSkar, SkarForm } from '../context/BlobContext';
import { Dices, Copy, Download, Check, Bookmark, Shapes, Circle, Square as SquareIcon, Triangle, Star, Share2, FileText, Upload, RotateCcw } from 'lucide-react';
import { motion, AnimatePresence } from 'motion/react';
import { useAuth } from '../context/AuthContext';

const COLOR_PALETTE = [
  '#00d2ff', '#34d399', '#22d3ee', '#f472b6', '#a78bfa', '#fbbf24', '#D74463',
  '#6366f1', '#ec4899', '#8b5cf6', '#10b981', '#f59e0b', '#ef4444', '#06b6d4',
  '#141414', '#ffffff', '#94a3b8', '#475569'
];

const FORMS: { id: SkarForm; icon: any; label: string }[] = [
  { id: 'skar', icon: Shapes, label: 'Skar' },
  { id: 'circle', icon: Circle, label: 'Circle' },
  { id: 'square', icon: SquareIcon, label: 'Square' },
  { id: 'triangle', icon: Triangle, label: 'Triangle' },
  { id: 'star', icon: Star, label: 'Star' },
];

export const BlobControls: React.FC = () => {
  const { 
    complexity, setComplexity, 
    contrast, setContrast, 
    color, setColor, 
    form, setForm,
    randomize, reset, path,
    saveToHistory,
    exportData,
    importData,
    styleMode // keep for report
  } = useSkar();
  const { user } = useAuth();
  const [copied, setCopied] = React.useState(false);
  const [saved, setSaved] = React.useState(false);
  const [showExport, setShowExport] = React.useState(false);
  const [importText, setImportText] = React.useState('');

  const handleCopy = () => {
    const svgCode = `<svg viewBox="0 0 400 400" xmlns="http://www.w3.org/2000/svg"><path d="${path}" fill="${color}"/></svg>`;
    navigator.clipboard.writeText(svgCode);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleSave = async () => {
    if (!user) return;
    await saveToHistory();
    setSaved(true);
    setTimeout(() => setSaved(false), 2000);
  };

  const handleDownload = () => {
    const svgCode = `<svg viewBox="0 0 400 400" xmlns="http://www.w3.org/2000/svg"><path d="${path}" fill="${color}"/></svg>`;
    const blob = new Blob([svgCode], { type: 'image/svg+xml' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `skarglass-${Date.now()}.svg`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  };

  const generateReport = () => {
    const report = `
SKARGLASS GENERATION REPORT
---------------------------
Date: ${new Date().toLocaleString()}
Form: ${form.toUpperCase()}
Style: ${styleMode.toUpperCase()}
Complexity: ${complexity}
Contrast: ${contrast}
Color: ${color}
SVG Path: ${path.substring(0, 50)}...
---------------------------
Generated by Skarglass AI
    `.trim();
    
    const blob = new Blob([report], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `skar-report-${Date.now()}.txt`;
    link.click();
    URL.revokeObjectURL(url);
  };

  const handleImport = () => {
    importData(importText);
    setShowExport(false);
    setImportText('');
  };

  return (
    <div className="flex flex-col gap-10 w-full mt-auto">
      {/* Forms Selector */}
      <div className="flex flex-col gap-4">
        <label className="text-[10px] font-black uppercase tracking-[0.2em] text-slate-400">Forms</label>
        <div className="flex flex-wrap gap-3">
          {FORMS.map((f) => {
            const Icon = f.icon;
            const isActive = form === f.id;
            return (
              <button
                key={f.id}
                onClick={() => setForm(f.id)}
                className={`flex items-center gap-2 px-4 py-3 rounded-2xl transition-all border shadow-lg backdrop-blur-2xl ${
                  isActive 
                    ? 'bg-slate-900 text-white border-slate-900 scale-105' 
                    : 'bg-white/40 text-slate-600 border-white/60 hover:bg-white/60'
                }`}
              >
                <Icon size={18} />
                <span className="text-xs font-black uppercase tracking-wider">{f.label}</span>
              </button>
            );
          })}
        </div>
      </div>

      {/* Sliders */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-10">
        <div className="flex flex-col gap-4">
          <div className="flex justify-between items-center">
            <label className="text-[10px] font-black uppercase tracking-[0.2em] text-slate-400">Complexity</label>
            <span className="text-xs font-black text-slate-800 bg-white/60 px-2 py-1 rounded-lg border border-white/80 shadow-sm">{complexity}</span>
          </div>
          <input 
            type="range" 
            min="3" 
            max="40" 
            value={complexity} 
            onChange={(e) => setComplexity(parseInt(e.target.value))}
            className="w-full h-2 bg-white/40 backdrop-blur-3xl rounded-full appearance-none cursor-pointer accent-slate-900 border border-white/80 shadow-inner"
          />
        </div>
        
        <div className="flex flex-col gap-4">
          <div className="flex justify-between items-center">
            <label className="text-[10px] font-black uppercase tracking-[0.2em] text-slate-400">Contrast</label>
            <span className="text-xs font-black text-slate-800 bg-white/60 px-2 py-1 rounded-lg border border-white/80 shadow-sm">{contrast}</span>
          </div>
          <input 
            type="range" 
            min="0" 
            max="100" 
            value={contrast} 
            onChange={(e) => setContrast(parseInt(e.target.value))}
            className="w-full h-2 bg-white/40 backdrop-blur-3xl rounded-full appearance-none cursor-pointer accent-slate-900 border border-white/80 shadow-inner"
          />
        </div>
      </div>

      {/* Color Table */}
      <div className="flex flex-col gap-4">
        <label className="text-[10px] font-black uppercase tracking-[0.2em] text-slate-400">Color Palette</label>
        <div className="grid grid-cols-6 md:grid-cols-9 gap-3 p-4 bg-white/30 backdrop-blur-3xl rounded-[2rem] border border-white/60 shadow-xl">
          {COLOR_PALETTE.map((c) => (
            <button
              key={c}
              onClick={() => setColor(c)}
              className={`w-full aspect-square rounded-xl transition-all border-2 ${color === c ? 'border-white scale-110 shadow-2xl z-10' : 'border-white/20 hover:scale-105'}`}
              style={{ backgroundColor: c }}
            />
          ))}
        </div>
      </div>

      {/* Actions */}
      <div className="flex flex-col md:flex-row items-center justify-between gap-8 pt-10 border-t border-white/40">
        <div className="flex items-center gap-4">
          <button 
            onClick={reset}
            className="p-4 bg-white/50 backdrop-blur-2xl text-slate-700 rounded-2xl border border-white/80 hover:bg-white/70 transition-all active:scale-95 shadow-lg"
            title="Reset to Default"
          >
            <RotateCcw size={22} />
          </button>
          <button 
            onClick={() => setShowExport(!showExport)}
            className="p-4 bg-white/50 backdrop-blur-2xl text-slate-700 rounded-2xl border border-white/80 hover:bg-white/70 transition-all active:scale-95 shadow-lg"
            title="AI Export/Import"
          >
            <Share2 size={22} />
          </button>
          <button 
            onClick={generateReport}
            className="p-4 bg-white/50 backdrop-blur-2xl text-slate-700 rounded-2xl border border-white/80 hover:bg-white/70 transition-all active:scale-95 shadow-lg"
            title="Export Report"
          >
            <FileText size={22} />
          </button>
        </div>

        <div className="flex items-center gap-4">
          {user && (
            <button 
              onClick={handleSave}
              className="p-4 bg-white/50 backdrop-blur-2xl text-slate-700 rounded-2xl border border-white/80 hover:bg-white/70 transition-all active:scale-95 shadow-lg flex items-center gap-2"
              title="Save to Library"
            >
              {saved ? <Check size={22} className="text-green-600" /> : <Bookmark size={22} />}
            </button>
          )}
          
          <button 
            onClick={handleDownload}
            className="p-4 bg-white/50 backdrop-blur-2xl text-slate-700 rounded-2xl border border-white/80 hover:bg-white/70 transition-all active:scale-95 shadow-lg"
            title="Download SVG"
          >
            <Download size={22} />
          </button>
          
          <button 
            onClick={handleCopy}
            className="p-4 bg-white/50 backdrop-blur-2xl text-slate-700 rounded-2xl border border-white/80 hover:bg-white/70 transition-all active:scale-95 flex items-center gap-2 shadow-lg"
            title="Copy SVG Code"
          >
            {copied ? <Check size={22} className="text-green-600" /> : <Copy size={22} />}
          </button>

          <button 
            onClick={randomize}
            className="px-8 py-4 bg-slate-900 text-white rounded-2xl font-black uppercase tracking-widest text-xs hover:bg-black transition-all active:scale-95 flex items-center gap-3 shadow-[0_20px_50px_rgba(0,0,0,0.2)]"
          >
            <Dices size={20} /> Randomize
          </button>
        </div>
      </div>

      {/* Export/Import Modal/Overlay */}
      <AnimatePresence>
        {showExport && (
          <motion.div 
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            exit={{ opacity: 0, y: 20 }}
            className="fixed inset-0 z-50 flex items-center justify-center p-6 bg-black/20 backdrop-blur-md"
          >
            <div className="w-full max-w-lg bg-white/90 backdrop-blur-3xl rounded-[2.5rem] border border-white p-8 shadow-2xl flex flex-col gap-6">
              <div className="flex justify-between items-center">
                <h3 className="font-black text-xl uppercase tracking-tighter">AI Interop</h3>
                <button onClick={() => setShowExport(false)} className="text-slate-400 hover:text-slate-900">✕</button>
              </div>
              
              <div className="flex flex-col gap-2">
                <label className="text-[10px] font-black uppercase tracking-widest text-slate-400">Export JSON</label>
                <textarea 
                  readOnly 
                  value={exportData()} 
                  className="w-full h-32 p-4 bg-white/50 border border-slate-200 rounded-2xl text-xs font-mono text-slate-600 resize-none"
                />
                <button 
                  onClick={() => {
                    navigator.clipboard.writeText(exportData());
                    alert('JSON copied to clipboard!');
                  }}
                  className="text-xs font-black text-slate-900 hover:underline text-left mt-1"
                >
                  Copy JSON
                </button>
              </div>

              <div className="flex flex-col gap-2">
                <label className="text-[10px] font-black uppercase tracking-widest text-slate-400">Import JSON</label>
                <textarea 
                  value={importText} 
                  onChange={(e) => setImportText(e.target.value)}
                  placeholder="Paste Skar JSON here..."
                  className="w-full h-32 p-4 bg-white/50 border border-slate-200 rounded-2xl text-xs font-mono text-slate-600 resize-none"
                />
                <button 
                  onClick={handleImport}
                  className="w-full py-4 bg-slate-900 text-white rounded-2xl font-black uppercase tracking-widest text-xs hover:bg-black transition-all flex items-center justify-center gap-2"
                >
                  <Upload size={16} /> Import Data
                </button>
              </div>
            </div>
          </motion.div>
        )}
      </AnimatePresence>
    </div>
  );
};
